# Generated by Django 5.1.7 on 2025-03-16 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersheetprogress",
            name="solved_easy",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersheetprogress",
            name="solved_hard",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="usersheetprogress",
            name="solved_medium",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
