# Generated by Django 5.1.7 on 2025-03-14 07:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_accepted",
            field=models.BooleanField(default=False),
        ),
    ]
