# Generated by Django 5.1.7 on 2025-03-14 15:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_customuser_is_accepted"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="date_joined",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="privilege",
            field=models.CharField(
                blank=True,
                choices=[
                    ("BRAHMIN", "Brahmin"),
                    ("KSHATRIYA", "Kshatriya"),
                    ("VAISHYA", "Vaishya"),
                    ("SHUDRA", "Shudra"),
                ],
                max_length=50,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="rank",
            field=models.CharField(
                blank=True, default="JADHAV", max_length=50, null=True
            ),
        ),
    ]
