# Generated by Django 5.1.7 on 2025-03-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_customuser_date_joined_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="profile_banner",
            field=models.ImageField(blank=True, null=True, upload_to="profile_banner/"),
        ),
    ]
